### ISSUE TITLE
Getting imageproxy creates error

### ISSUE THREAD

**Issue by dsarosi** [willnorris/imageproxy#172]
When running `go get willnorris.com/go/imageproxy` the following error occurs.

`# willnorris.com/go/imageproxy
../../../willnorris.com/go/imageproxy/transform.go:173:13: undefined: smartcrop.SmartCrop`

**Comment by efabian** [comment]
Encountered the same error.

**Comment by willnorris** [comment]
Yep, I see what happened here.  I've been using go modules support pretty much exclusively, so I've been pinned at an older version of the smartcrop package.  I removed the vendor directory last night, with the intention of pushing toward always building with module support.  So that's one option... checkout the project outside of your GOPATH and build with go1.11 or later.

But the other thing I need to do is update to the latest version of smartcrop, so that building without modules will still work.  I'll do that later today.  Thanks for reporting this!  I totally overlooked in the work I was doing last night.

**Comment by dsarosi** [comment]
It's working.  Thanks for the quick update.
